# Generated by Django 3.1.7 on 2021-08-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checkout',
            new_name='Order',
        ),
    ]
