# Generated by Django 3.2.7 on 2021-10-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.IntegerField(default=''),
        ),
    ]
