# Generated by Django 3.1.7 on 2021-08-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210812_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_method',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
