# Generated by Django 3.1.7 on 2021-08-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_order_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_method',
            field=models.CharField(default='', max_length=50),
        ),
    ]
