# Generated by Django 3.1.7 on 2021-12-03 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20211203_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='image_p',
            new_name='image_of_product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='price_p',
            new_name='price_of_the_product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='name_p',
        ),
        migrations.AddField(
            model_name='cart',
            name='name_of_the_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
