# Generated by Django 3.1.7 on 2021-08-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210816_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order_method',
        ),
        migrations.AddField(
            model_name='order',
            name='order_method',
            field=models.CharField(default='', max_length=50),
        ),
    ]
