# Generated by Django 3.1.7 on 2021-12-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20211203_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='name_of_the_product',
            field=models.CharField(default='', max_length=50),
        ),
    ]
