# Generated by Django 3.1.7 on 2021-08-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210823_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
