# Generated by Django 3.1.7 on 2021-08-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210823_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product_price',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
