# Generated by Django 3.1.7 on 2021-12-03 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20211203_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='name_of_the_product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
