# Generated by Django 3.1.7 on 2021-08-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210824_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_image',
            field=models.ImageField(default=1, upload_to='shop/images'),
            preserve_default=False,
        ),
    ]
