# Generated by Django 3.1.7 on 2021-12-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20211203_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='name_of_the_product',
            new_name='product_name',
        ),
    ]
