# Generated by Django 3.1.7 on 2021-08-25 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='order_id',
        ),
    ]
