# Generated by Django 3.1.7 on 2021-08-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210825_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_uid',
            field=models.CharField(default=0, max_length=100000),
        ),
    ]
