# Generated by Django 3.1.7 on 2021-08-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_order_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_uid',
            field=models.IntegerField(default=0),
        ),
    ]
