# Generated by Django 4.0 on 2022-02-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_order_product_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_image',
            field=models.ImageField(upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='shop/images'),
        ),
    ]
