# Generated by Django 3.1.7 on 2021-08-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20210825_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_uid',
            new_name='user_uid',
        ),
    ]
