# Generated by Django 3.1.7 on 2021-08-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20210825_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
