# Generated by Django 4.0 on 2022-02-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_product_subcategory_delete_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
