# Generated by Django 3.1.7 on 2021-08-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20210830_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_id',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
