# Generated by Django 3.1.7 on 2021-08-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_order_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='admin_id',
            field=models.IntegerField(default=''),
        ),
    ]
