# Generated by Django 3.1.7 on 2021-08-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20210830_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='admin_id',
            field=models.IntegerField(default=''),
        ),
    ]
