# Generated by Django 4.0 on 2022-02-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_product_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
