# Generated by Django 3.2.7 on 2021-09-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20210930_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='id',
        ),
    ]
