# Generated by Django 4.0 on 2022-09-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_bulk_email_register_attempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register_Attempt',
        ),
    ]
